### ISSUE TITLE
`samsrf_revcor_cf` still asks for data in double precision

### ISSUE THREAD

**Issue by mmejia23** [samsrf/samsrf#2]
I'm using version 9, where the default is single precision data. But when running `samsrf_revcor_cf`, at the line 204 when calling `samsrf_cfparam_loop`, it stops with an error saying "The input points must be a double array."

When I changed the defaults to `def_64bit = true`, the error is gone. I tried to debug a bit more to isolate the problem, but not much success. I'm not sure if it was something about my data (though, everything was in single when the error occurred), or if that specific function needs to update to 32bit.

**Comment by samsrf** [comment]
Thanks for letting me know. The single-precision was largely meant for the forward-model pRF analysis because it really speeds that up. The reverse correlation algorithms are generally quite fast so it shouldn't make that much of a difference there (other than saving disc space). There are some functions in Matlab that require double-precision though. I'll investigate what the issue is.

**Comment by samsrf** [comment]
Hi again, as of v9.82 this issue should now be fixed - but let me know if there are still issues. I'm sorry for the delay in dealing with this. For my sanity I don't get notifications about issues from GitHub and I was far too busy in the past few months to have much a look on here.
